backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/listings"
public_folder: "/assets/images/listings"

collections:
  - name: "listings"
    label: "Listings"
    folder: "content/listings"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Bedrooms", name: "bedrooms", widget: "number" }
      - { label: "Bathrooms", name: "bathrooms", widget: "number" }
      - { label: "Size (mÂ²)", name: "size", widget: "number" }
      - label: "Images"
        name: "images"
        widget: "list"
        field:
          { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
