backend:
  name: git-gateway
  branch: main

media_folder: "images/properties"
public_folder: "/images/properties"

collections:
  - name: "properties"
    label: "Properties"
    folder: "_properties"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - label: "Gallery Images"
        name: "images"
        widget: "list"
        field: { label: "Image", name: "image", widget: "image" }
